[package]
name = "clip_key_sanitizer"
version = "0.1.0"
edition = "2021"
authors = ["mosure <mitchell@mosure.me>"]
exclude = ["dist", "build", "assets", "credits"]

[dependencies]
clipboard = "0.5.0"
device_query = "1.1.3"
enigo = "0.1.3"
trie-rs = "0.1.1"
